### ISSUE TITLE
Non-scam conversations (CallHome dataset)

### ISSUE THREAD

**Issue by thurairajulaganathan** [aliderakhsh/Detecting-Telephone-based-Social-Engineering-Attacks-using-Scam-Signatures-Dataset#1]
Hi sir,

Can I get CallHome dataset in excel file? Currently I am doing research regarding scam and non-scam attacks, it will be extremely helpful 
if this dataset is accessible for me.
Your help is much appreciated.

Thank you sir.

**Comment by aliderakhsh** [comment]
Hi,

I'm glad that you are interested in this research paper, I have attached
the English version of the CallHome dataset to this email. Thank you.

**Comment by thurairajulaganathan** [comment]
Hi sir, 

Thanks for your email, but I haven’t received the attachment sir. Can you resend the email with the attachment sir?

Thank you so much for your support sir.

**Comment by aliderakhsh** [comment]
Hi Ulaganathan,

Can you send me your email address? So that I can forward it.

**Comment by thurairajulaganathan** [comment]
Hi sir,

Sure. This is my email address: bi19160348@student.ums.edu.my
I greatly appreciate your help sir.

Thank you sir.

**Comment by aliderakhsh** [comment]
Hi,

The non-scam conversations are available in [this link](https://ca.talkbank.org/access/CallHome/eng.html) and click on "Download transcripts" to download them. Thank you.

**Comment by thurairajulaganathan** [comment]
Hi sir,

Got it sir I can download it. 
I appreciate your help sir.

Thank you so much for your support sir.

**Comment by thurairajulaganathan** [comment]
Hi sir,

Thanks for your email, but I haven’t received the attachment sir. Can you
resend the email with the attachment sir?

Thank you so much for your support sir.

Regards,
Thurairaj Ulaganathan
